### ISSUE TITLE
Fails to play - Streamlink error

### ISSUE THREAD

**Issue by unlocKing** [beardypig/plugin.video.blxdtvcatchup#1]
Will  not play any channel, log info:
```
04:53:48 T:6756  NOTICE: [xbmcswift2] Request for "/" matches rule for function "index"
04:53:51 T:11360   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named pycountry
                                            Traceback (most recent call last):
                                              File "C:\Users\j\AppData\Roaming\Kodi\addons\plugin.video.streamlink\addon.py", line 6, in <module>
                                                import streamlink
                                              File "C:\Users\j\AppData\Roaming\Kodi\addons\plugin.video.streamlink\lib\streamlink\__init__.py", line 73, in <module>
                                                from .api import streams
                                              File "C:\Users\j\AppData\Roaming\Kodi\addons\plugin.video.streamlink\lib\streamlink\api.py", line 1, in <module>
                                                from .session import Streamlink
                                              File "C:\Users\j\AppData\Roaming\Kodi\addons\plugin.video.streamlink\lib\streamlink\session.py", line 9, in <module>
                                                from streamlink.utils.l10n import Localization
                                              File "C:\Users\j\AppData\Roaming\Kodi\addons\plugin.video.streamlink\lib\streamlink\utils\l10n.py", line 11, in <module>
                                                from pycountry import languages, countries
                                            ImportError: No module named pycountry
                                            -->End of Python script error report<--
04:53:51 T:3228   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.streamlink/play?url=http%3A//tvcatchup.com/watch/bbctwo]
```

**Comment by beardypig** [comment]
Thanks for reporting this @unlocKing, I missed it on the kodi forums... :( 

I have fixed the issues with the streamlink plugin, and thus the tvcatchup plugin.

**Comment by unlocKing** [comment]
I know your really active here with streamlink, so knew you would see this. Thanks dude!

Still getting an error, but it has got further:

```
15:18:13 T:11504  NOTICE: [xbmcswift2] Request for "/" matches rule for function "index"
15:18:15 T:9024  NOTICE: [xbmcswift2] Request for "/play" matches rule for function "play_stream"
15:18:15 T:9024  NOTICE: [plugin.video.streamlink] Trying to find a stream to play on http://tvcatchup.com/watch/bbctwo
15:18:16 T:9024   ERROR: C:\Users\j\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\packages\urllib3\util\ssl_.py:334: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
                                              SNIMissingWarning
15:18:16 T:9024   ERROR: C:\Users\j\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\packages\urllib3\util\ssl_.py:132: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
                                              InsecurePlatformWarning
15:18:16 T:9024   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'streamlink.exceptions.PluginError'>
                                            Error Contents: Unable to open URL: https://s58.cdn.tvcatchup.com/pshift_sess_5899e53649c4b/bbctwo_adp.m3u8?clientKey=0391e3c4a578906caefe1ae4b595191c-MTQ4NjQ4Nzg5NA==&device=web&channelid=2&channel=2 ([Errno 1] _ssl.c:510: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed)
                                            Traceback (most recent call last):
                                              File "C:\Users\j\AppData\Roaming\Kodi\addons\plugin.video.streamlink\addon.py", line 73, in <module>
                                                plugin.run()
                                              File "C:\Users\j\AppData\Roaming\Kodi\addons\script.module.xbmcswift2\lib\xbmcswift2\plugin.py", line 332, in run
                                                items = self._dispatch(self.request.path)
                                              File "C:\Users\j\AppData\Roaming\Kodi\addons\script.module.xbmcswift2\lib\xbmcswift2\plugin.py", line 306, in _dispatch
                                                listitems = view_func(**items)
                                              File "C:\Users\j\AppData\Roaming\Kodi\addons\plugin.video.streamlink\addon.py", line 43, in play_stream
                                                streams = session.streams(url)
                                              File "C:\Users\j\AppData\Roaming\Kodi\addons\plugin.video.streamlink\lib\streamlink\session.py", line 424, in streams
                                                return plugin.streams(**params)
                                              File "C:\Users\j\AppData\Roaming\Kodi\addons\plugin.video.streamlink\lib\streamlink\plugin\plugin.py", line 240, in streams
                                                raise PluginError(err)
                                            PluginError: Unable to open URL: https://s58.cdn.tvcatchup.com/pshift_sess_5899e53649c4b/bbctwo_adp.m3u8?clientKey=0391e3c4a578906caefe1ae4b595191c-MTQ4NjQ4Nzg5NA==&device=web&channelid=2&channel=2 ([Errno 1] _ssl.c:510: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed)
                                            -->End of Python script error report<--
15:18:16 T:12212   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.streamlink/play?url=http%3A//tvcatchup.com/watch/bbctwo]
```

**Comment by unlocKing** [comment]
Should've mentioned I'm using SPMC and Kodi 16.1.. not 17 if that makes a difference.

**Comment by beardypig** [comment]
It's because of an old version of Python. Kodi 16 still has ancient Python ssl libraries :\ I think the only way around it on Windows is to install a newer Kodi version, 17 in this case.

**Comment by beardypig** [comment]
As for SPMC I have no experience with that :)

**Comment by unlocKing** [comment]
Cool, I've been trying to avoid the upgrade.. but it looks like it has to happen now for this and MPEG-DASH support.

I'll install 17 and report back if any issues arise.

Cheers!

**Comment by beardypig** [comment]
OK. I thinking I might rewrite this plugin anyway, add some improvements and not use streamlink - as it's a bit of overkill. Should be able to support Kodi 16 with the new version :)

**Comment by unlocKing** [comment]
Probably a good idea, I've read a lot of people aren't ready to make the jump to 17 yet, so it will get more users.

**Comment by beardypig** [comment]
@unlocKing I have updated the plugin (version 2.0.0), it should now work with Kodi 16 :) It doesn't use `streamlink` any more either.
